### ISSUE TITLE
iLogic - Vault search error

### ISSUE THREAD

**Issue by Jedyd** [koechlm/iLogic-Vault#14]
Hi Markus, thank you for sharing, I tried to reproduce the setting in the class handout, but I get an error message when running the iLogic rule, do I need to change anything?
![Fehlermeldung iLogic - Vault](https://user-images.githubusercontent.com/68946681/112214618-b1cfea00-8c1f-11eb-849d-b754e4bf3a21.JPG)

**Comment by Jedyd** [comment]
it works, i have previously written an error in Search Params. Could you please tell me where i can download the additional materials for the design re-use unlimited?

**Comment by koechlm** [comment]
@Jedyd: Glad to see that you resolved the issue on your own. The additional material is part of the AU downloads: https://www.autodesk.com/autodesk-university/class/iLogic-and-Vault-Vault-and-iLogic-2020#downloads. "Materials".

**Comment by Jedyd** [comment]
I'll make it in my environment, thank you very much!
I ask myself the question for customers who did not use Vault, but only Inventor. Do you have made iLogic Rule that can guarantee the same function? Configure modules only within Inventor with form and copy the corresponding variant (like copy iLogic Design) to create the corresponding drawing

**Comment by koechlm** [comment]
You cannot achieve the same without Vault; managing the key parameters and search for them is a PDM only benefit.
