### ISSUE TITLE
Compilation for the Vault 2021.26.2.24.0 version and the ability to add cheeks to the database

### ISSUE THREAD

**Issue by Wirgili** [koechlm/iLogic-Vault#21]
I have vault client 2021.2.4 and vault server 2021.2.4. I export ipt and iam files to the .step format, which I would like to automatically add to the database. Is it possible to use the latest build of this add-on 2023 for my version 2021.2.4?
Regards

Wirgi

**Comment by koechlm** [comment]
Hello @Wirgili, it is possible. You need to replace the SDK references and update the version number backward like you would do upgrading an existing code to the latest.

**Comment by Wirgili** [comment]
Hello, Will I find documentation for migration somewhere ?

**Comment by koechlm** [comment]
The documentation on required references and the API version number is in the SDK 'Getting Started' chapter. So in your case, it is even easier - make a screenshot of the references assemblies, then delete these and re-add these from the 2021 SDK. Then update the API version number (replace 16.0 with 14.0 for the 2021 version). This should be all you need to do for a successful compilation.

**Comment by Wirgili** [comment]
Hello, I still have a problem with compiling the server library, all references have been defined correctly

![image](https://user-images.githubusercontent.com/110233233/182227930-d5b345bf-e4c3-4131-aff7-fe2be56996e1.png)

**Comment by koechlm** [comment]
Yes, there is a change for user authentication from 2021 and later. So you need to go back to the 2021 compatible syntax, that you can review on the GitHub repository by activating the 2021 branch: replace the highlighted line with; AWT.UserIdTicketCredentials mCred = new AWT.UserIdTicketCredentials(mSrvIdnts, VaultName, UserId, Ticket);
You will also need to adapt this in Job Rules: goto the latest 2021 based rule template of https://github.com/koechlm/Vault-Job-Processor---iLogic-Extension/blob/2021.1.0/Autodesk.VltInvSrv.iLogicSampleJob/VaultJobRuleConnected.iLogicVb
