### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/iLogic-Vault#5]
Hello,

This is realy nice thing for Vault users and CAD administrator. 

This solution get file to user workspace, what is litle bit dangerous, because user can had some old version of file on his local drive. It will be good if file and workspace can be at some temp folder.

There is also some problem on polish version with loging. Extension working for me if i comment this line:  //      mLogCtrl.SaveLogAs(mILogicLogFileFullName);

![image](https://user-images.githubusercontent.com/61918020/76152623-cd725c00-60c1-11ea-91a2-5967bf35d4bb.png)

In another case I'm geting exception:"
Job failed by unhandled exception: System.InvalidOperationException: Brak aktualnego pliku dziennika.
   w System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   w CallSite.Target(Closure , CallSite , ComObject , String )
   w System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   w System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   w Autodesk.VltInvSrv.iLogicSampleJob.JobExtension.Execute(IJobProcessorServices context, IJob job) w C:\Users\koechlm\source\Autodesk.VltInvSrv.iLogicSampleJob\Autodesk.VltInvSrv.iLogicSampleJob\JobExtension.cs:wiersz 471
"

**Comment by koechlm** [comment]
Hello Dariusz,
thank you for the feedback. As it relates to the Job for the iLogic Support project, let's move the conversation there.
Thanks,
Markus
