### ISSUE TITLE
Function Get Properties of File

### ISSUE THREAD

**Issue by TWiesendanger** [koechlm/iLogic-Vault#7]
Ich hatte letztens den Fall, dass ich mit der Suchfunktion super mein File suchen und gefunden werden konnte. Danach war aber die Aufgabe ein Property des gefunden Files mit dem aktuell geöffneten zu vergleichen. Den einzigen Weg dazu wäre vermutlich nur, dass File herunterzuladen und danach das lokale File anzusprechen. Das wollte ich aber eigentlich verhindern.

Schöner wär ein Funktion um mit dem gefundenen Namen die Properties aus dem Vault abzufragen.

**Comment by koechlm** [comment]
Thanks for the reasonable requirement. The implementation is feasible and will go into the next major update.

**Comment by koechlm** [comment]
@TWiesendanger : speaking from an iLogic perspective I suggest to deliver all file properties/values as an Inventor NameValueMap object. Do you agree that this enables any iLogic author consuming the file's Vault properties?

**Comment by TWiesendanger** [comment]
Yes definitely that would have helped in my case.
