### ISSUE TITLE
Vault Basic

### ISSUE THREAD

**Issue by AmanBa3** [koechlm/iLogic-Vault#9]
Hallo,
wir versuchen wie viel wie möglich "i" Sachen in unseren Workflow auszunutzen aber traurigerweise haben wir auf ein Problem aufgestoßen. Veil wir die Basic Version von Vault benutzen, haben wir keine Möglichkeit "Revision control" frei zum kontrollieren und in diesen Projekt befindet sich die Revision Gathering Option. Ist es möglich eine Library zu machen, die für uns Basic Benutzer, "out of the box" arbeitet konnte?
Ich rate das diese Sache unser Problem ist. Leider ist mein wissen zu niedrig um selber weiter klar zum kommen. Vielen Dank.
In Anhang befinden sie sich ein Paar Bilder von den error und die Zeile die ich vermute das uns das ärger macht. 
![Error](https://user-images.githubusercontent.com/71550672/94403999-8f787a80-016e-11eb-9b06-a4a43d796c9a.JPG)
![Project](https://user-images.githubusercontent.com/71550672/94404007-9606f200-016e-11eb-9a72-d28fa51a0151.JPG)

**Comment by koechlm** [comment]
Technically, it might be an option to include options supporting different Vault editions. I will evaluate legal restrictions and depending on the result put it as a future requirement.

**Comment by koechlm** [comment]
Getting back to share insights and my decision on how to proceed with requests on Vault Basic: In theory, we could use the Basic Webservices API to communicate with the Vault server. I reviewed the library and concluded NOT to limit the scope to any flavor below Vault Professional. My intent is to share a broad range of implementation options and future versions are going to include ITEM, ECO, and CUSTENT (Custom Objects) objects. There is an Idea Station thread asking do add iLogic-Vault to the core product. You may add the requirement to differentiate Workgroup and Professional there.
